# Generated by Django 6.1 on 2026-08-21 17:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=100)),
                ('variedade', models.CharField(blank=True, max_length=100, null=True)),
                ('data_plantio', models.DateField(blank=True, null=True)),
                ('ciclo_dias_estimado', models.PositiveIntegerField(verbose_name='Ciclo (dias)')),
                ('status', models.CharField(choices=[('PREPARO', 'Preparo do talhão'), ('ATIVO', 'Ativo / Em desenvolvimento'), ('COLHEITA', 'Em Colheita'), ('FINALIZADO', 'Finalizado')], default='PREPARO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('Praga', 'Praga'), ('Doença', 'Doença'), ('Deficiência Nutricional', 'Deficiência Nutricional'), ('Dano Climático', 'Dano Climático'), ('Outro', 'Outro')], max_length=100)),
                ('descricao', models.TextField()),
                ('acao_tomada', models.TextField(blank=True, null=True)),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='core.plantio')),
            ],
        ),
        migrations.CreateModel(
            name='Manejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('tipo_operacao', models.CharField(choices=[('Adubação de Fundação', 'Adubação de Fundação'), ('Adubação de Cobertura', 'Adubação de Cobertura'), ('Pulverização/Defensivo', 'Pulverização/Defensivo'), ('Poda/Desbrota', 'Poda/Desbrota'), ('Capina/Roçada', 'Capina/Roçada'), ('Tratos Culturais', 'Tratos Culturais')], max_length=100)),
                ('produto_insumo', models.CharField(max_length=150)),
                ('dosagem_quantidade', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manejos', to='core.plantio')),
            ],
        ),
        migrations.CreateModel(
            name='Irrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracao_minutos', models.PositiveIntegerField()),
                ('lamina_ou_volume', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=200, null=True)),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigacoes', to='core.plantio')),
            ],
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (m²)')),
                ('tipo_solo', models.CharField(choices=[('Arenoso', 'Arenoso'), ('Argiloso', 'Argiloso'), ('Misto', 'Misto'), ('Siltoso', 'Siltoso'), ('Outro', 'Outro')], default='Misto', max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plantio',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantios', to='core.talhao'),
        ),
    ]
