# Generated by Django 6.1 on 2026-08-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talhao',
            name='coordenadas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
