# Generated by Django 6.1 on 2026-08-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_talhao_coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantio',
            name='ciclo_dias_estimado',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Ciclo (dias)'),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='cultura',
            field=models.CharField(blank=True, default='Preparo de Solo', max_length=100, null=True),
        ),
    ]
