# Generated by Django 6.1 on 2026-08-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_plantio_ciclo_dias_estimado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manejo',
            name='tipo_operacao',
            field=models.CharField(choices=[('Adubação de Fundação', 'Adubação de Fundação'), ('Adubação de Cobertura', 'Adubação de Cobertura'), ('Pulverização/Defensivo', 'Pulverização/Defensivo'), ('Poda/Desbrota', 'Poda/Desbrota'), ('Capina/Roçada', 'Capina/Roçada'), ('Tratos Culturais', 'Tratos Culturais'), ('Colheita', 'Colheita')], max_length=100),
        ),
    ]
