# Generated by Django 6.1 on 2026-09-03 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_propriedade_talhao_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='contorno_geojson',
            field=models.JSONField(blank=True, help_text='Coordenadas do perímetro da propriedade', null=True),
        ),
        migrations.AlterField(
            model_name='irrigacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manejo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='coordenadas_json',
            field=models.JSONField(blank=True, help_text='Polígono do talhão no mapa [[lat, lng], ...]', null=True),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='propriedade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='core.propriedade'),
        ),
    ]
