# Generated by Django 6.1 on 2026-09-18 10:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_propriedade_contorno_geojson_alter_irrigacao_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talhao',
            name='sistema_irrigacao',
            field=models.CharField(choices=[('GOTEJAMENTO', 'Gotejamento'), ('ASPERSAO', 'Aspersão'), ('MICROASPERSAO', 'Microaspersão'), ('PIVO', 'Pivô Central'), ('SEQUEIRO', 'Sequeiro / Sem Irrigação')], default='SEQUEIRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='ciclo_dias_estimado',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ciclo (dias)'),
        ),
        migrations.CreateModel(
            name='RegistroIrrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_irrigacao', models.DateField(default=django.utils.timezone.now)),
                ('duracao_horas', models.DecimalField(blank=True, decimal_places=2, help_text='Tempo de rega em horas', max_digits=5, null=True)),
                ('volume_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Volume estimado em mm (L/m²)', max_digits=5, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_irrigacao', to='core.plantio')),
            ],
        ),
    ]
