# Generated by Django 6.1 on 2026-09-18 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_talhao_sistema_irrigacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroirrigacao',
            name='hora_irrigacao',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
